debug: false
base-url: "."
salt: "8hAl9athiI"
default-interface: "10.0.0.2:8080"

#session encryption key
encryption-key: "uyM7mkmN6u"

#set default host and scheme to avoid empty host redirect
default-host: "warthunder.com"
default-scheme: "http"

recaptcha:
  public-key: "6LdqGScUAAAAALUWNs7FewFMw-h0ZpX4WnUay84v"
  private-key: "6LdqGScUAAAAAG0o_rCtzHswX4mSY_I2027gEGO2"
  src: "https://www.google.com/recaptcha/api.js"
  api: "https://www.google.com/recaptcha/api/siteverify"
  action-url: "/proxycheck/"
  background: "https://static.warthunder.ru/i/bg-fon/wt_1-71_ru_1.jpg?v=2"

stat:
  host: "10.0.0.1"
  port: 8125

sensu:
  address: "10.0.0.1:3030"
